version: '3.5'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=yii_test
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=password
    ports:
      - '33061:3306'
    volumes:
      - ./mysql:/etc/dump

